// Fluent Signal style reminder: this page is Bharani's operating-system canvas. Preserve acrylic depth, calm chrome, cyan live signals, and discoverability.
import { useEffect, useRef, useState } from "react";
import type { CSSProperties, PointerEvent, ReactNode } from "react";
import type { LucideIcon } from "lucide-react";
import { Activity, BatteryFull, Bot, BriefcaseBusiness, Calculator, ChevronRight, CloudSun, Code2, Globe2, HardDrive, LockKeyhole, Mail, Maximize2, Menu, Minus, Search, Settings2, Share2, Terminal as TerminalIcon, Trophy, UserRound, Volume2, Wifi, X } from "lucide-react";
import { appIconUrls, profile, repos, signalMarkUrl, wallpaperUrl } from "@/lib/portfolioData";
import { AboutApp, AchievementsApp, AppId, AppSectionHeader, ExplorerApp, ProjectHubApp, SocialsApp, StatsApp, StatusPill, TechApp } from "@/components/PortfolioApps";
import { BrowserApp, CalculatorApp, NotificationPanel, SettingsApp, TerminalApp, WeatherApp } from "@/components/SystemApps";
import { AboutWorkstationApp } from "@/components/AboutWorkstationApp";
import { ContactApp, PortfolioAssistantApp } from "@/components/AssistantContactApps";
import { isSoundMuted, playSystemSound, setSoundMuted } from "@/lib/soundManager";
import { clearSavedWallpaper, restoreWallpaper, saveUploadedWallpaper, saveWallpaperUrl, type WallpaperAsset } from "@/lib/wallpaperManager";
import { useLiveGitHub, useLiveWeather, useRuntimeStatus, useVisitorLocation } from "@/lib/liveData";
import { accentOptions, clearCustomization, defaultCustomization, readCustomization, writeCustomization, type DesktopCustomization } from "@/lib/customizationManager";

type FullAppId = AppId | "terminal" | "browser" | "settings" | "calculator" | "weather" | "assistant" | "contact";
type WindowState = { id: FullAppId; minimized: boolean; maximized: boolean; x: number; y: number; w: number; h: number };
type DragState = { id: FullAppId; offsetX: number; offsetY: number; nextX: number; nextY: number } | null;
type DesktopStyle = CSSProperties & Record<`--${string}`, string>;

const appMeta: Record<FullAppId, { title: string; short: string; icon: LucideIcon; image: string; color: string }> = {
  explorer: { title: "This PC", short: "This PC", icon: HardDrive, image: appIconUrls.explorer, color: "#b9b6b0" },
  about: { title: "About Me", short: "About Me", icon: UserRound, image: appIconUrls.about, color: "#c6c0b5" },
  projects: { title: "Project Hub", short: "Project Hub", icon: BriefcaseBusiness, image: appIconUrls.projects, color: "#d49a5c" },
  tech: { title: "Tech Stack", short: "Tech Stack", icon: Code2, image: appIconUrls.tech, color: "#d0a77c" },
  achievements: { title: "Achievements", short: "Achievements", icon: Trophy, image: appIconUrls.achievements, color: "#d4b477" },
  socials: { title: "Connect Everywhere", short: "Socials", icon: Share2, image: appIconUrls.socials, color: "#bfb8ae" },
  stats: { title: "GitHub Power", short: "GitHub Power", icon: Activity, image: appIconUrls.stats, color: "#9dd5b5" },
  terminal: { title: "vanta-code — Terminal", short: "Terminal", icon: TerminalIcon, image: appIconUrls.terminal, color: "#a9d5bd" },
  browser: { title: "Microsoft Edge", short: "Live Demos", icon: Globe2, image: appIconUrls.browser, color: "#d0a77c" },
  settings: { title: "Settings", short: "Settings", icon: Settings2, image: appIconUrls.settings, color: "#c2bdb3" },
  calculator: { title: "Calculator", short: "Calculator", icon: Calculator, image: appIconUrls.calculator, color: "#b7a4d8" },
  weather: { title: "Atmosphere", short: "Weather", icon: CloudSun, image: appIconUrls.weather, color: "#e2be77" },
  assistant: { title: "Portfolio Assistant", short: "Assistant", icon: Bot, image: signalMarkUrl, color: "#d49a5c" },
  contact: { title: "Contact Bharani", short: "Contact", icon: Mail, image: profile.avatar, color: "#d49a5c" },
};
const requestedApp = typeof window !== "undefined" ? new URLSearchParams(window.location.search).get("app") as FullAppId | null : null;
const initialApp = requestedApp && appMeta[requestedApp] ? requestedApp : "about";
const initialWindows: WindowState[] = [{ id: initialApp, minimized: false, maximized: false, x: 142, y: 78, w: initialApp === "browser" ? 930 : 820, h: initialApp === "browser" ? 590 : 560 }];
const DEFAULT_WALLPAPER: WallpaperAsset = { kind: "image", source: "default", src: wallpaperUrl, name: "Graphite Ember" };
const desktopApps: FullAppId[] = ["explorer", "projects", "about", "tech", "achievements", "socials", "assistant", "contact"];
const pinnedApps: FullAppId[] = ["explorer", "projects", "assistant", "contact", "terminal", "browser", "tech"];

function formatTime(date: Date) { return date.toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit", hour12: false }); }
function formatDate(date: Date) { return date.toLocaleDateString(undefined, { weekday: "short", day: "2-digit", month: "2-digit", year: "numeric" }); }
function AppGlyph({ id, size = 20 }: { id: FullAppId; size?: number }) { const [failed, setFailed] = useState(false); const Fallback = appMeta[id].icon; return failed ? <Fallback className="app-icon-fallback" size={size} aria-hidden="true" /> : <img className="app-raster-icon" src={appMeta[id].image} width={size} height={size} alt="" decoding="async" onError={() => setFailed(true)} />; }

function WallpaperMedia({ wallpaper }: { wallpaper: WallpaperAsset }) { return wallpaper.kind === "video" ? <video className="wallpaper-media" src={wallpaper.src} autoPlay muted loop playsInline aria-hidden="true" /> : null; }

function WindowShell({ win, active, onFocus, onClose, onMinimize, onMaximize, onTitlePointerDown, children }: { win: WindowState; active: boolean; onFocus: () => void; onClose: () => void; onMinimize: () => void; onMaximize: () => void; onTitlePointerDown: (event: PointerEvent<HTMLDivElement>) => void; children: ReactNode }) {
  const meta = appMeta[win.id]; const style: CSSProperties | undefined = win.maximized ? undefined : { left: win.x, top: win.y, width: win.w, height: win.h };
  return <section className={`os-window ${active ? "window-active" : ""} ${win.maximized ? "window-maximized" : ""}`} style={style} onPointerDown={onFocus} aria-label={meta.title}><div className="window-titlebar" onPointerDown={onTitlePointerDown} onDoubleClick={onMaximize}><div className="window-title"><AppGlyph id={win.id} size={15} /><span>{meta.title}</span></div><div className="window-controls" onPointerDown={(event) => event.stopPropagation()} onDoubleClick={(event) => event.stopPropagation()}><button aria-label="Minimize" onClick={onMinimize}><Minus size={15} /></button><button aria-label="Maximize" onClick={onMaximize}><Maximize2 size={13} /></button><button aria-label="Close" className="close-control" onClick={onClose}><X size={15} /></button></div></div><div className="window-body">{children}</div></section>;
}

function WindowContent({ id, openApp, wallpaper, wallpaperBusy, onWallpaperFile, onWallpaperUrl, onWallpaperReset, visitorLocation, weather }: { id: FullAppId; openApp: (id: FullAppId) => void; lightMode: boolean; setLightMode: (value: boolean) => void; soundEnabled: boolean; setSoundEnabled: (value: boolean) => void; wallpaper: WallpaperAsset; wallpaperBusy: boolean; onWallpaperFile: (file: File) => void; onWallpaperUrl: (url: string) => void; onWallpaperReset: () => void; visitorLocation: ReturnType<typeof useVisitorLocation>; weather: ReturnType<typeof useLiveWeather> }) {
  const activeCustomization = readCustomization();
  const applyCustomization = (changes: Partial<DesktopCustomization>) => { const next = { ...readCustomization(), ...changes }; writeCustomization(next); window.dispatchEvent(new CustomEvent<DesktopCustomization>("developer-os-customization", { detail: next })); };
  const resetCustomization = () => { clearCustomization(); window.dispatchEvent(new CustomEvent<DesktopCustomization>("developer-os-customization", { detail: defaultCustomization })); };
  if (id === "about") return <AboutWorkstationApp openApp={(app) => openApp(app)} />;
  if (id === "projects") return <ProjectHubApp />;
  if (id === "explorer") return <ExplorerApp openApp={(app) => openApp(app)} />;
  if (id === "tech") return <TechApp />;
  if (id === "achievements") return <AchievementsApp />;
  if (id === "socials") return <SocialsApp />;
  if (id === "stats") return <StatsApp />;
  if (id === "terminal") return <TerminalApp />;
  if (id === "browser") return <BrowserApp />;
  if (id === "settings") return <SettingsApp customization={activeCustomization} onCustomizationChange={applyCustomization} onCustomizationReset={resetCustomization} wallpaper={wallpaper} wallpaperBusy={wallpaperBusy} onWallpaperFile={onWallpaperFile} onWallpaperUrl={onWallpaperUrl} onWallpaperReset={onWallpaperReset} />;
  if (id === "calculator") return <CalculatorApp />;
  if (id === "assistant") return <PortfolioAssistantApp />;
  if (id === "contact") return <ContactApp />;
  return <WeatherApp location={visitorLocation} weather={weather} />;
}

function LoginScreen({ now, onLogin, wallpaper, githubSnapshot }: { now: Date; onLogin: () => void; wallpaper: WallpaperAsset; githubSnapshot: ReturnType<typeof useLiveGitHub>["data"] }) {
  return <main className="login-screen" style={wallpaper.kind === "image" ? { backgroundImage: `linear-gradient(180deg, rgba(65,55,45,.24), rgba(29,28,27,.78)), url(${wallpaper.src})` } : undefined}><WallpaperMedia wallpaper={wallpaper} /><div className="login-topbar"><span className="login-language">ENG <ChevronRight size={13} /></span><span className="login-network"><Wifi size={16} /><Volume2 size={16} /><BatteryFull size={16} /></span></div><div className="login-center"><div className="login-time">{formatTime(now)}</div><div className="login-date">{formatDate(now)}</div><div className="login-account"><div className="login-avatar"><img src={profile.avatar} alt={profile.name} /></div><h1>{profile.name}</h1><p>{profile.role}</p><button className="login-button" onClick={onLogin}>Sign in <ChevronRight size={16} /></button><small>Press Enter to open Bharani's workstation</small></div></div><div className="login-footer"><div className="login-footer-line"><span>BHARANI / SYSTEMS</span><span className="footer-signal"><span className="presence-dot" /> {githubSnapshot ? `${githubSnapshot.publicRepos} public repositories` : "GitHub snapshot unavailable"}</span></div></div></main>;
}

export default function Home() {
  const [loggedIn, setLoggedIn] = useState(() => new URLSearchParams(window.location.search).has("desktop")); const [now, setNow] = useState(() => new Date()); const [windows, setWindows] = useState<WindowState[]>(initialWindows); const [activeId, setActiveId] = useState<FullAppId>(initialApp); const [startOpen, setStartOpen] = useState(false); const [notificationOpen, setNotificationOpen] = useState(false); const [startQuery, setStartQuery] = useState(""); const [contextOpen, setContextOpen] = useState(false); const [contextPosition, setContextPosition] = useState({ x: 210, y: 150 }); const [customization, setCustomization] = useState<DesktopCustomization>(() => { const saved = readCustomization(); return { ...saved, soundEnabled: saved.soundEnabled && !isSoundMuted() }; }); const [wallpaper, setWallpaper] = useState<WallpaperAsset>(DEFAULT_WALLPAPER); const [wallpaperBusy, setWallpaperBusy] = useState(true); const dragRef = useRef<DragState>(null);
  const runtime = useRuntimeStatus();
  const visitorLocation = useVisitorLocation();
  const weather = useLiveWeather(visitorLocation.coordinates);
  const { data: githubSnapshot } = useLiveGitHub();
  const updateCustomization = (changes: Partial<DesktopCustomization>) => { setCustomization((current) => { const next = { ...current, ...changes }; writeCustomization(next); if ("soundEnabled" in changes) { setSoundMuted(!next.soundEnabled); if (next.soundEnabled) playSystemSound("notification"); } return next; }); };
  const resetCustomization = () => { clearCustomization(); setSoundMuted(!defaultCustomization.soundEnabled); setCustomization(defaultCustomization); };
  const lightMode = customization.lightMode;
  const soundEnabled = customization.soundEnabled;
  const setLightMode = (value: boolean) => updateCustomization({ lightMode: value });
  const setSoundEnabled = (value: boolean) => updateCustomization({ soundEnabled: value });
  const setWallpaperFromFile = async (file: File) => { setWallpaperBusy(true); try { const next = await saveUploadedWallpaper(file); setWallpaper((current) => { if (current.source === "upload" && current.src.startsWith("blob:")) URL.revokeObjectURL(current.src); return next; }); } finally { setWallpaperBusy(false); } };
  const setWallpaperFromUrl = (url: string) => { setWallpaper(saveWallpaperUrl(url)); };
  const resetWallpaper = async () => { setWallpaperBusy(true); await clearSavedWallpaper(); setWallpaper(DEFAULT_WALLPAPER); setWallpaperBusy(false); };
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { let alive = true; restoreWallpaper().then((saved) => { if (alive && saved) setWallpaper(saved); }).finally(() => { if (alive) setWallpaperBusy(false); }); return () => { alive = false; }; }, []);
  useEffect(() => { const receiveCustomization = (event: Event) => { const next = (event as CustomEvent<DesktopCustomization>).detail; if (!next) return; setSoundMuted(!next.soundEnabled); setCustomization(next); }; window.addEventListener("developer-os-customization", receiveCustomization); return () => window.removeEventListener("developer-os-customization", receiveCustomization); }, []);
  useEffect(() => { const root = document.documentElement; const body = document.body; root.style.setProperty("--signal", accentOptions[customization.accent].value); body.dataset.taskbarAlignment = customization.taskbarAlignment; body.dataset.taskbarSize = customization.taskbarSize; body.dataset.iconScale = customization.iconScale; body.dataset.textScale = customization.textScale; body.dataset.reducedMotion = String(customization.reducedMotion); return () => { delete body.dataset.taskbarAlignment; delete body.dataset.taskbarSize; delete body.dataset.iconScale; delete body.dataset.textScale; delete body.dataset.reducedMotion; }; }, [customization]);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (!loggedIn) { if (event.key === "Enter") { playSystemSound("login"); setLoggedIn(true); } return; } if (event.key === "/" && document.activeElement?.tagName !== "INPUT") { event.preventDefault(); playSystemSound("menu"); setStartOpen(true); window.setTimeout(() => document.getElementById("start-search")?.focus(), 20); } if (event.key === "Escape") { setStartOpen(false); setNotificationOpen(false); setContextOpen(false); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [loggedIn]);
  useEffect(() => { if (loggedIn && visitorLocation.status === "idle") visitorLocation.requestLocation(); }, [loggedIn, visitorLocation.requestLocation, visitorLocation.status]);
  const openApp = (id: FullAppId) => { playSystemSound("open"); setStartOpen(false); setNotificationOpen(false); setContextOpen(false); setActiveId(id); setWindows((current) => { const exists = current.find((item) => item.id === id); if (exists) return current.map((item) => item.id === id ? { ...item, minimized: false } : item); const wide = id === "projects" || id === "explorer" || id === "browser" || id === "assistant" || id === "contact"; return [...current, { id, minimized: false, maximized: false, x: 170 + current.length * 18, y: 84 + current.length * 12, w: wide ? 930 : 790, h: wide ? 590 : 540 }]; }); };
  const closeApp = (id: FullAppId) => { playSystemSound("close"); setWindows((current) => current.filter((item) => item.id !== id)); }; const minimizeApp = (id: FullAppId) => { playSystemSound("close"); setWindows((current) => current.map((item) => item.id === id ? { ...item, minimized: true } : item)); }; const maximizeApp = (id: FullAppId) => { playSystemSound("open"); setWindows((current) => current.map((item) => item.id === id ? { ...item, maximized: !item.maximized, minimized: false } : item)); };
  const dragFrameRef = useRef<number | null>(null);
  const handleTitlePointerDown = (event: PointerEvent<HTMLDivElement>, id: FullAppId) => { const win = windows.find((item) => item.id === id); if (!win || win.maximized) return; event.currentTarget.setPointerCapture?.(event.pointerId); dragRef.current = { id, offsetX: event.clientX - win.x, offsetY: event.clientY - win.y, nextX: win.x, nextY: win.y }; setActiveId(id); playSystemSound("focus"); };
  const handlePointerMove = (event: PointerEvent<HTMLDivElement>) => { const drag = dragRef.current; if (!drag) return; const win = windows.find((item) => item.id === drag.id); if (!win) return; const maxX = Math.max(8, event.currentTarget.clientWidth - win.w - 8); const maxY = Math.max(38, event.currentTarget.clientHeight - win.h - 76); drag.nextX = Math.min(maxX, Math.max(8, event.clientX - drag.offsetX)); drag.nextY = Math.min(maxY, Math.max(38, event.clientY - drag.offsetY)); if (dragFrameRef.current !== null) return; dragFrameRef.current = window.requestAnimationFrame(() => { dragFrameRef.current = null; const latest = dragRef.current; if (!latest) return; setWindows((current) => current.map((item) => item.id === latest.id ? { ...item, x: latest.nextX, y: latest.nextY } : item)); }); };
  const handlePointerUp = () => { if (dragFrameRef.current !== null) { window.cancelAnimationFrame(dragFrameRef.current); dragFrameRef.current = null; } const drag = dragRef.current; if (drag) setWindows((current) => current.map((item) => item.id === drag.id ? { ...item, x: drag.nextX, y: drag.nextY } : item)); dragRef.current = null; };
  const filteredApps = (Object.keys(appMeta) as FullAppId[]).filter((id) => `${appMeta[id].title} ${appMeta[id].short}`.toLowerCase().includes(startQuery.toLowerCase())); const allWindowsMinimized = windows.length > 0 && windows.every((item) => item.minimized);
  if (!loggedIn) return <LoginScreen now={now} wallpaper={wallpaper} githubSnapshot={githubSnapshot} onLogin={() => { playSystemSound("login"); setLoggedIn(true); }} />;
  return <main className={`desktop-shell ${lightMode ? "light-preview" : ""}`} style={wallpaper.kind === "image" ? { backgroundImage: `linear-gradient(130deg, rgba(65,55,45,.5), rgba(29,28,27,.35)), url(${wallpaper.src})` } : undefined} onPointerMove={handlePointerMove} onPointerUp={handlePointerUp} onContextMenu={(event) => { event.preventDefault(); playSystemSound("menu"); setContextPosition({ x: Math.min(event.clientX, Math.max(12, window.innerWidth - 190)), y: Math.min(event.clientY, Math.max(55, window.innerHeight - 190)) }); setContextOpen(true); setStartOpen(false); }} onClick={() => setContextOpen(false)}><WallpaperMedia wallpaper={wallpaper} /><div className="desktop-glow glow-one" /><div className="desktop-glow glow-two" /><div className="desktop-brand"><img src={signalMarkUrl} alt="" /><div><strong>BHARANI / SYSTEMS</strong><span>PERSONAL WORKSTATION</span></div></div><div className="desktop-icons">{desktopApps.map((id) => <button className="desktop-icon" key={id} aria-label={`Open ${appMeta[id].title}`} onDoubleClick={(event) => { event.stopPropagation(); openApp(id); }} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); openApp(id); } }} onClick={(event) => { event.stopPropagation(); setActiveId(id); }}><span className="desktop-icon-box"><AppGlyph id={id} size={25} /></span><span>{appMeta[id].short}</span></button>)}</div><div className="system-widget"><div className="widget-live"><span className={`presence-dot ${runtime.online ? "" : "status-offline"}`} /> {runtime.online ? "BROWSER ONLINE" : "OFFLINE"}</div><div className="widget-time">{formatTime(now)}</div><div className="widget-sub">{formatDate(now)} · {visitorLocation.label ?? visitorLocation.timeZone}</div>{runtime.heapPercent !== null && <div className="widget-progress"><span style={{ width: `${runtime.heapPercent}%` }} /></div>}<div className="widget-foot"><span>{visitorLocation.status === "granted" ? "LOCATION ACTIVE" : visitorLocation.status === "requesting" ? "REQUESTING LOCATION" : runtime.visible ? "WINDOW VISIBLE" : "WINDOW HIDDEN"}</span><b>{runtime.heapPercent === null ? "N/A" : `${runtime.heapPercent}% HEAP`}</b></div></div><div className="window-layer">{windows.filter((win) => !win.minimized).map((win) => <WindowShell key={win.id} win={win} active={activeId === win.id} onFocus={() => { setActiveId(win.id); playSystemSound("focus"); }} onClose={() => closeApp(win.id)} onMinimize={() => minimizeApp(win.id)} onMaximize={() => maximizeApp(win.id)} onTitlePointerDown={(event) => handleTitlePointerDown(event, win.id)}><WindowContent id={win.id} openApp={openApp} lightMode={lightMode} setLightMode={setLightMode} soundEnabled={soundEnabled} setSoundEnabled={setSoundEnabled} wallpaper={wallpaper} wallpaperBusy={wallpaperBusy} onWallpaperFile={setWallpaperFromFile} onWallpaperUrl={setWallpaperFromUrl} onWallpaperReset={resetWallpaper} visitorLocation={visitorLocation} weather={weather} /></WindowShell>)}</div>
    {contextOpen && <div className="context-menu" style={{ left: contextPosition.x, top: contextPosition.y }} onClick={(event) => event.stopPropagation()}><button onClick={() => setStartOpen(true)}><Search size={14} /> Search apps</button><button onClick={() => openApp("settings")}><Settings2 size={14} /> Personalize</button><button onClick={() => openApp("projects")}><Activity size={14} /> Refresh GitHub snapshot</button></div>}
    {startOpen && <div className="start-menu" onClick={(event) => event.stopPropagation()}><div className="start-search"><Search size={16} /><input id="start-search" value={startQuery} onChange={(event) => setStartQuery(event.target.value)} placeholder="Search apps, projects, files..." autoFocus /></div><div className="start-heading"><span>Pinned</span><button onClick={() => setStartQuery("")}>All apps <ChevronRight size={13} /></button></div><div className="pinned-grid">{filteredApps.slice(0, 8).map((id) => <button key={id} onClick={() => openApp(id)}><span className="start-app-icon"><AppGlyph id={id} size={19} /></span><span>{appMeta[id].short}</span></button>)}</div><div className="start-heading recommended-heading"><span>Recommended</span><button onClick={() => openApp("projects")}>See all <ChevronRight size={13} /></button></div><div className="recommended-list"><button onClick={() => openApp("projects")}><div className="recommend-icon"><BriefcaseBusiness size={17} /></div><div><strong>Project Hub</strong><span>{githubSnapshot ? `${githubSnapshot.publicRepos} public repositories` : "GitHub snapshot loading"}</span></div><small>{githubSnapshot ? "live snapshot" : "loading"}</small></button><button onClick={() => openApp("terminal")}><div className="recommend-icon"><TerminalIcon size={17} /></div><div><strong>vanta-code terminal</strong><span>Local terminal surface</span></div><small>available</small></button></div><div className="start-footer"><div className="start-user"><div className="mini-avatar"><img src={profile.avatar} alt="" /></div><span>{profile.name}</span></div><button onClick={() => setLoggedIn(false)} aria-label="Sign out"><LockKeyhole size={15} /></button></div></div>}
    {notificationOpen && <NotificationPanel onClose={() => setNotificationOpen(false)} soundEnabled={soundEnabled} setSoundEnabled={setSoundEnabled} />}
    <nav className="taskbar" onClick={(event) => event.stopPropagation()}><button className="start-button" aria-label="Start" onClick={() => { playSystemSound("menu"); setStartOpen(!startOpen); setNotificationOpen(false); }}><img src={signalMarkUrl} alt="" /></button><div className="taskbar-search" role="button" tabIndex={0} aria-label="Search apps" onClick={() => { playSystemSound("menu"); setStartOpen(true); window.setTimeout(() => document.getElementById("start-search")?.focus(), 20); }} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setStartOpen(true); document.getElementById("start-search")?.focus(); } }}><Search size={15} /><span>Search</span></div><div className="taskbar-pinned">{pinnedApps.map((id) => <button aria-label={appMeta[id].title} className={activeId === id ? "taskbar-app taskbar-active" : "taskbar-app"} key={id} onClick={() => openApp(id)}><AppGlyph id={id} size={19} /></button>)}</div><div className="taskbar-spacer" /><div className="tray"><button className="tray-button" aria-label="Quick settings" onClick={() => { playSystemSound("menu"); setNotificationOpen(!notificationOpen); setStartOpen(false); }}><Wifi size={14} /><Volume2 size={14} /><BatteryFull size={15} /></button><button className="clock" aria-label="Open weather" onClick={() => openApp("weather")}><span>{formatTime(now)}</span><small>{formatDate(now)}</small></button><button className={`show-desktop ${allWindowsMinimized ? "show-desktop-active" : ""}`} aria-label="Show desktop" onClick={() => { playSystemSound("close"); setWindows((current) => current.map((item) => ({ ...item, minimized: !allWindowsMinimized }))); }} /></div></nav></main>;
}
