// Fluent Signal style reminder: this is a believable profile workstation, not a marketing hero—use system metadata, file-like panels, and quiet signal states.
import { Activity, ArrowUpRight, CheckCircle2, CircleDot, Cpu, Github, MapPin, Play, Radio, ShieldCheck, Terminal, UserRound } from "lucide-react";
import { profile, signalMarkUrl } from "@/lib/portfolioData";
import { StatusPill } from "@/components/PortfolioApps";
import { useLiveGitHub, useRuntimeStatus } from "@/lib/liveData";

export function AboutWorkstationApp({ openApp }: { openApp: (id: "projects" | "tech") => void }) {
  const { data: githubSnapshot } = useLiveGitHub();
  const runtime = useRuntimeStatus();
  return <div className="app-scroll workstation-app">
    <div className="workstation-filebar"><div className="workstation-path"><span>PERSONAL WORKSTATION</span><b>/</b><strong>profile.bharani</strong></div><div className="workstation-meta"><span><span className={`presence-dot ${runtime.online ? "" : "status-offline"}`} /> {runtime.online ? "BROWSER ONLINE" : "OFFLINE"}</span><span>{githubSnapshot ? "GITHUB SNAPSHOT" : "SNAPSHOT LOADING"}</span></div></div>
    <div className="workstation-heading"><div className="workstation-identity"><div className="identity-mark"><img src={signalMarkUrl} alt="Bharani Systems signal mark" /></div><div><div className="eyebrow cyan-label"><CircleDot size={12} /> ACTIVE PROFILE</div><h1>{profile.name}</h1><p>{profile.role}</p></div></div><div className="workstation-actions"><button className="primary-button" onClick={() => openApp("projects")}><Play size={14} /> Open project index</button><a className="ghost-button" href={profile.github} target="_blank" rel="noreferrer"><Github size={14} /> Source profile <ArrowUpRight size={12} /></a></div></div>
    <div className="workstation-summary"><div className="summary-main"><div className="summary-label"><Terminal size={13} /> /etc/profile/README</div><p>{profile.bio}</p><div className="profile-quote">“{profile.tagline}”</div></div><div className="summary-portrait"><img src={profile.avatar} alt={profile.name} /><span><span className="presence-dot" /> open to collaborate</span></div></div>
    <div className="workstation-panels"><div className="workstation-panel"><div className="panel-kicker">IDENTITY <span>SOURCED</span></div><div className="detail-line"><MapPin size={14} /><span>Base</span><b>{profile.location}</b></div><div className="detail-line"><UserRound size={14} /><span>Education</span><b>{profile.education}</b></div><div className="detail-line"><Cpu size={14} /><span>Learning</span><b>{profile.learning.join(" · ")}</b></div></div><div className="workstation-panel"><div className="panel-kicker">CURRENT BUILDS <span>{profile.currentBuilds.length} LISTED</span></div>{profile.currentBuilds.map((item, index) => <div className="process-line" key={item}><span className="process-index">0{index + 1}</span><div><strong>{item}</strong><small>{["voice · vision · agents", "screen intelligence · cursor-aware", "multimodal circuit analysis"][index]}</small></div><StatusPill status="building" /></div>)}</div><div className="workstation-panel signal-health"><div className="panel-kicker">BROWSER RUNTIME <span>{runtime.visible ? "VISIBLE" : "HIDDEN"}</span></div><div className="health-orb"><Activity size={17} /><strong>{runtime.heapPercent === null ? "—" : `${runtime.heapPercent}%`}</strong></div><div className="health-copy"><span><CheckCircle2 size={13} /> {githubSnapshot ? "GitHub API snapshot loaded" : "GitHub API snapshot pending"}</span><span><ShieldCheck size={13} /> {runtime.online ? "Network online" : "Offline mode"}</span><span><Radio size={13} /> Profile timezone: {profile.timezone}</span></div></div></div>
    <div className="workstation-footer"><span>profile.bharani · read-only surface</span><button onClick={() => openApp("tech")}>Inspect toolchain <ArrowUpRight size={13} /></button></div>
  </div>;
}
