// Fluent Signal style reminder: portfolio apps use acrylic surfaces, restrained cyan live signals, and dense but readable system metadata.
import { useMemo, useState } from "react";
import type { CSSProperties, ReactNode } from "react";
import {
  Activity, ArrowUpRight, BriefcaseBusiness, CheckCircle2, ChevronRight, CircleDot,
  Code2, Cpu, ExternalLink, FileText, Folder, FolderOpen, Github, Globe2,
  GraduationCap, HardDrive, Mail, MapPin, Play, Radio, Search, Share2, Sparkles,
  Star, Trophy, UserRound, Zap,
} from "lucide-react";
import {
  achievements, liveDemos, profile, projectBackdropUrl, repos, signalMarkUrl,
  skills, socials, stats, textureUrl, type PortfolioRepo,
} from "@/lib/portfolioData";

export type AppId = "explorer" | "about" | "projects" | "tech" | "achievements" | "socials" | "stats";
type OpenApp = (id: AppId) => void;

export function AppSectionHeader({ eyebrow, title, subtitle, right }: { eyebrow: string; title: string; subtitle?: string; right?: ReactNode }) {
  return <header className="app-section-header"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{right}</header>;
}

export function StatusPill({ status }: { status: PortfolioRepo["status"] }) {
  const labels = { live: "LIVE", building: "BUILDING", prototype: "PROTOTYPE", fork: "FORK" };
  return <span className={`status-pill status-${status}`}><span className="status-dot" />{labels[status]}</span>;
}

export function AboutApp({ openApp }: { openApp: OpenApp }) {
  return <div className="app-scroll about-app" style={{ backgroundImage: `linear-gradient(110deg, rgba(7,20,29,.98), rgba(7,20,29,.78)), url(${textureUrl})` }}>
    <div className="about-hero"><div className="about-copy"><div className="eyebrow cyan-label"><CircleDot size={12} /> LIVE PROFILE</div><h1>Engineering intelligence<br /><span>into systems.</span></h1><p>{profile.bio}</p><div className="hero-actions"><button className="primary-button" onClick={() => openApp("projects")}><Play size={15} /> Explore projects</button><a className="ghost-button" href={profile.github} target="_blank" rel="noreferrer"><Github size={15} /> GitHub <ArrowUpRight size={13} /></a></div></div><div className="avatar-card"><div className="avatar-ring"><img src={profile.avatar} alt={profile.name} /></div><div className="avatar-status"><span className="presence-dot" /> Open to collaborate</div><div className="avatar-code">BK<span>/</span>SYS</div></div></div>
    <div className="about-grid"><div className="info-card"><div className="info-card-title"><MapPin size={15} /> BASED IN</div><strong>{profile.location}</strong><span>{profile.timezone}</span></div><div className="info-card"><div className="info-card-title"><GraduationCap size={15} /> CURRENTLY</div><strong>{profile.education}</strong><span>Computer Science & Engineering</span></div><div className="info-card"><div className="info-card-title"><Radio size={15} /> FOCUS</div><strong>{profile.currentBuilds.join(" · ")}</strong><span>Building the next signal</span></div></div>
    <div className="about-lower"><div className="build-panel"><div className="panel-kicker">THE WORKBENCH <span>03 ACTIVE THREADS</span></div>{profile.currentBuilds.map((item, index) => <div className="build-row" key={item}><div className="build-index">0{index + 1}</div><div><strong>{item}</strong><span>{["Autonomous AI · voice · vision · agents", "Real-time screen intelligence · cursor-aware", "Circuit board reverse engineering · multimodal"][index]}</span></div><StatusPill status="building" /></div>)}</div><div className="signal-panel"><div className="panel-kicker">A QUICK READ</div><p>“{profile.tagline}”</p><div className="signal-rule"><span /> <small>70+ AI PROJECTS · REAL-WORLD IMPACT</small></div><button className="text-button" onClick={() => openApp("tech")}>View my stack <ChevronRight size={14} /></button></div></div>
  </div>;
}

export function ProjectHubApp() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [status, setStatus] = useState("All");
  const categories = ["All", "AI Systems", "Product", "Games", "Systems", "Design", "Computer Vision", "Experiments"];
  const filtered = useMemo(() => repos.filter((item) => { const matchesQuery = `${item.name} ${item.description} ${item.language}`.toLowerCase().includes(query.toLowerCase()); const matchesCategory = category === "All" || item.category === category; const matchesStatus = status === "All" || item.status === status.toLowerCase(); return matchesQuery && matchesCategory && matchesStatus; }), [query, category, status]);
  return <div className="app-scroll projects-app" style={{ backgroundImage: `linear-gradient(100deg, rgba(5,15,23,.98) 0%, rgba(5,15,23,.86) 44%, rgba(5,15,23,.56) 100%), url(${projectBackdropUrl})` }}><AppSectionHeader eyebrow="PORTFOLIO INDEX / 65 REPOSITORIES" title="Project Hub" subtitle="Steam-style live cards. Every public system, one searchable machine." right={<div className="index-count"><strong>{filtered.length}</strong><span>shown</span></div>} /><div className="project-toolbar"><div className="inline-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search every project..." /><kbd>/</kbd></div><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter by status"><option>All</option><option>Live</option><option>Building</option><option>Prototype</option></select></div><div className="chip-row">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={category === item ? "chip active-chip" : "chip"}>{item}</button>)}</div><div className="project-grid">{filtered.map((item, index) => <article className={`project-card ${item.featured ? "featured-project" : ""}`} key={item.name} style={{ "--delay": `${Math.min(index, 12) * 22}ms` } as CSSProperties}><div className="project-card-top"><span className="project-number">{String(index + 1).padStart(2, "0")}</span><StatusPill status={item.status} /><span className="star-count"><Star size={12} fill="currentColor" /> {item.stars}</span></div><h3>{item.name}</h3><p>{item.description}</p><div className="project-card-footer"><span className="language-dot" /> {item.language}<span className="project-category">{item.category}</span>{item.homepage && <a href={item.homepage} target="_blank" rel="noreferrer" aria-label={`Open ${item.name} demo`}><ExternalLink size={14} /></a>}<a href={`https://github.com/${profile.handle}/${item.name}`} target="_blank" rel="noreferrer" aria-label={`Open ${item.name} GitHub`}><Github size={14} /></a></div></article>)}</div></div>;
}

export function ExplorerApp({ openApp }: { openApp: OpenApp }) {
  const [folder, setFolder] = useState("All Projects");
  const groups = ["Quick access", "All Projects", "Core AI Systems", "Live Demos", "In Development", "Hackathons", "Resume & Files"];
  const items = folder === "Core AI Systems" ? repos.filter((item) => item.category === "AI Systems" && item.featured) : folder === "Live Demos" ? liveDemos : folder === "In Development" ? repos.filter((item) => item.status === "building") : folder === "Hackathons" ? repos.filter((item) => ["SocialGuard-RL", "PrivatePulse-AI"].includes(item.name)) : repos;
  return <div className="explorer-app"><aside className="explorer-sidebar"><div className="explorer-profile"><div className="mini-avatar"><img src={profile.avatar} alt="" /></div><div><strong>{profile.handle}</strong><span>Personal workstation</span></div></div>{groups.map((item, index) => <button key={item} className={folder === item ? "explorer-nav active-explorer" : "explorer-nav"} onClick={() => setFolder(item)}>{index === 0 ? <Zap size={15} /> : index === 6 ? <FileText size={15} /> : <Folder size={15} />}<span>{item}</span>{index === 1 && <small>65</small>}</button>)}<div className="storage-card"><div className="storage-head"><HardDrive size={15} /><span>Local Disk (C:)</span></div><div className="storage-bar"><span /></div><small>Portfolio OS · 65 systems indexed</small></div></aside><div className="explorer-main"><div className="explorer-topbar"><div className="crumb"><ChevronRight size={14} /><span>{folder}</span></div><div className="explorer-actions"><button><Search size={14} /> Sort</button><button><FolderOpen size={14} /> View</button></div></div><div className="explorer-hero"><div><div className="eyebrow">THIS PC / PERSONAL WORKSPACE</div><h2>{folder}</h2><p>Everything Bharani is building, shipped, and still thinking through.</p></div><div className="explorer-hero-mark"><img src={signalMarkUrl} alt="Signal mark" /></div></div><div className="file-grid">{items.map((item) => <button className="file-item" key={item.name} onDoubleClick={() => openApp("projects")}><div className="file-icon"><FolderOpen size={26} /></div><strong>{item.name}</strong><span>{item.language} · {item.status}</span></button>)}</div></div></div>;
}

export function TechApp() {
  return <div className="app-scroll tech-app"><AppSectionHeader eyebrow="TOOLCHAIN / GENERATED FROM REPO DATA" title="Tech Stack" subtitle="The tools behind the systems." right={<div className="tech-chip"><Cpu size={15} /> SYSTEMS READY</div>} /><div className="skill-layout"><div className="skill-list">{Object.entries(skills).map(([group, items]) => <div className="skill-group" key={group}><div className="skill-group-title"><span>{group}</span><small>{items.length} tools</small></div><div className="skill-tags">{items.map((item) => <span key={item}>{item}</span>)}</div></div>)}</div><div className="radar-card"><div className="panel-kicker">SIGNAL RADAR</div><div className="radar-orb"><div className="radar-ring ring-one" /><div className="radar-ring ring-two" /><div className="radar-cross cross-x" /><div className="radar-cross cross-y" /><div className="radar-core"><Sparkles size={20} /></div><div className="radar-label label-ai">AI / ML</div><div className="radar-label label-stack">FULL STACK</div><div className="radar-label label-sys">SYSTEMS</div></div><div className="signal-bars">{stats.systems.map(([label, value]) => <div className="signal-bar-row" key={label}><span>{label}</span><div><i style={{ width: `${value}%` }} /></div><b>{value}</b></div>)}</div></div></div></div>;
}

export function AchievementsApp() {
  return <div className="app-scroll achievements-app"><AppSectionHeader eyebrow="MILESTONES / SHIPPED UNDER PRESSURE" title="Achievements" subtitle="Three submissions. One consistent direction: build the system." /><div className="achievement-hero"><div className="achievement-number">03</div><div><div className="eyebrow cyan-label"><Trophy size={13} /> HACKATHONS & SUBMISSIONS</div><h3>Ideas become environments<br /><span>when the clock is running.</span></h3></div><div className="trophy-glow"><Trophy size={42} /></div></div><div className="achievement-list">{achievements.map(([event, project, result, description], index) => <article className="achievement-row" key={event}><div className="achievement-index">0{index + 1}</div><div className="achievement-content"><div className="achievement-event">{event}</div><h3>{project}</h3><p>{description}</p></div><div className="achievement-result"><CheckCircle2 size={15} /> {result}</div><a href={`https://github.com/${profile.handle}/${project}`} target="_blank" rel="noreferrer"><ArrowUpRight size={16} /></a></article>)}</div><div className="quote-card"><span className="quote-mark">“</span><p>The ones who are crazy enough to think they can change the world, are the ones who do.</p><small>— Steve Jobs · found in the Secret folder</small></div></div>;
}

export function SocialsApp() {
  return <div className="app-scroll socials-app"><AppSectionHeader eyebrow="CONTACT DIRECTORY / 22 ENDPOINTS" title="Connect Everywhere" subtitle="The internet is a wide room. Here are all the doors." right={<a className="mail-button" href={`mailto:${profile.email}`}><Mail size={15} /> Send a signal</a>} /><div className="social-grid">{socials.map(([name, handle, url], index) => <a className="social-card" href={url} target="_blank" rel="noreferrer" key={name}><div className={`social-badge social-${index % 6}`}><span>{name.slice(0, 1)}</span></div><div><strong>{name}</strong><small>{handle}</small></div><ArrowUpRight size={14} /></a>)}</div><div className="contact-footer"><Mail size={16} /><span>{profile.email}</span><a href={`mailto:${profile.email}`}>Open mail composer <ArrowUpRight size={14} /></a></div></div>;
}

export function StatsApp() {
  return <div className="app-scroll stats-app"><AppSectionHeader eyebrow="GITHUB POWER / LIVE WIDGETS" title="Stats & Activity" subtitle="Real numbers move. The dashboard keeps the signal visible." right={<span className="live-readout"><span className="presence-dot" /> LIVE INDEX</span>} /><div className="stat-cards"><div><span>PUBLIC REPOS</span><strong>{stats.publicRepos}</strong><small>across every system</small></div><div><span>AI PROJECTS</span><strong>{stats.claimedAiProjects}</strong><small>claimed in profile</small></div><div><span>FEATURED STARS</span><strong>19–33</strong><small>per public repo snapshot</small></div><div><span>OPEN TO</span><strong>BUILD</strong><small>collaborate · learn · ship</small></div></div><div className="stats-visual-grid"><div className="github-widget-card"><div className="widget-heading"><Github size={16} /> README STATS <span>github-readme-stats</span></div><img src="https://github-readme-stats.vercel.app/api?username=vincenzo-afk&show_icons=true&theme=transparent&hide_border=true&title_color=00e0ff&text_color=c7d9e6&icon_color=58a6ff&bg_color=00000000" alt="GitHub statistics" /></div><div className="github-widget-card"><div className="widget-heading"><Activity size={16} /> CONTRIBUTION ACTIVITY <span>last 12 months</span></div><img src="https://github-readme-activity-graph.vercel.app/graph?username=vincenzo-afk&theme=github-compact&bg_color=00000000&color=00e0ff&line=58a6ff&point=ffffff&area=true&hide_border=true" alt="GitHub contribution graph" /></div></div><div className="stat-footer"><div className="mini-chart"><div className="panel-kicker">SYSTEM MOMENTUM</div><div className="bars">{[42, 58, 51, 68, 61, 78, 72, 88, 82, 96, 91, 100].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div><div className="chart-labels"><span>JAN</span><span>JUN</span><span>NOW</span></div></div><div className="stats-note"><Zap size={17} /><p>Stats are intentionally treated as a live layer — profile views, followers, stars, streak, top languages, trophies, and coding activity can change without redesigning the machine.</p></div></div></div>;
}
