// Fluent Signal style reminder: system apps should feel native, quiet, and useful, with cyan reserved for active controls and verified states.
import { useRef, useState } from "react";
import { Activity, BatteryFull, ChevronRight, CloudSun, Menu, Radio, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Star, Terminal as TerminalIcon, Volume2, Wifi, X, Zap } from "lucide-react";
import { liveDemos, profile, terminalCommands, wallpaperUrl } from "@/lib/portfolioData";

export function TerminalApp() {
  const [lines, setLines] = useState<string[]>(["vanta-code v5.0.0 · Bharani Systems", "Type help to inspect the available commands.", ""]);
  const [input, setInput] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);
  const submit = () => { const command = input.trim(); if (!command) return; const result = terminalCommands[command as keyof typeof terminalCommands] || `command not found: ${command}. Try help.`; setLines((current) => [...current, `> ${command}`, result, ""]); setInput(""); };
  return <div className="terminal-app" onClick={() => inputRef.current?.focus()}><div className="terminal-topline"><span className="terminal-dot red" /><span className="terminal-dot yellow" /><span className="terminal-dot green" /><span className="terminal-path">~/bharani-systems</span><span className="terminal-state">● connected</span></div><div className="terminal-output">{lines.map((line, index) => <div className={line.startsWith(">") ? "terminal-command" : index < 2 ? "terminal-intro" : ""} key={`${line}-${index}`}>{line || "\u00a0"}</div>)}<div className="terminal-input-line"><span>bk@nova:~$</span><input ref={inputRef} value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => event.key === "Enter" && submit()} aria-label="Terminal command" autoFocus /><span className="cursor-block" /></div></div><div className="terminal-hints"><button onClick={() => { setInput("projects"); inputRef.current?.focus(); }}>projects</button><button onClick={() => { setInput("stats"); inputRef.current?.focus(); }}>stats</button><button onClick={() => { setInput("sudo hire-me"); inputRef.current?.focus(); }}>sudo hire-me</button></div></div>;
}

export function BrowserApp() {
  return <div className="browser-app"><div className="browser-toolbar"><button><Menu size={16} /></button><button><ChevronRight size={16} /></button><div className="address-bar"><ShieldCheck size={14} /><span>vincenzo-afk.vercel.app / live projects</span><Star size={13} /></div><button><Menu size={16} /></button></div><div className="browser-body"><div className="browser-hero"><div className="eyebrow">BHARANI / LIVE WEB</div><h2>Shipped systems,<br /><span>open in a tab.</span></h2><p>Working demos and public surfaces from the portfolio index.</p></div><div className="demo-list">{liveDemos.slice(0, 18).map((item) => <a href={item.homepage} target="_blank" rel="noreferrer" className="demo-row" key={item.name}><span className="demo-favicon"><Wifi size={14} /></span><div><strong>{item.name}</strong><small>{item.homepage?.replace("https://", "")}</small></div><span className="demo-status">LIVE</span><ChevronRight size={14} /></a>)}</div></div></div>;
}

export function SettingsApp({ lightMode, setLightMode }: { lightMode: boolean; setLightMode: (value: boolean) => void }) {
  return <div className="settings-app"><aside className="settings-sidebar"><div className="settings-user"><div className="mini-avatar"><img src={profile.avatar} alt="" /></div><div><strong>{profile.name}</strong><span>Personalization</span></div></div>{["System", "Bluetooth & devices", "Network & internet", "Personalization", "Apps", "Accounts", "Time & language"].map((item, index) => <button className={item === "Personalization" ? "settings-nav active-settings" : "settings-nav"} key={item}><Settings2 size={15} style={{ opacity: index === 3 ? 1 : .58 }} />{item}</button>)}</aside><div className="settings-main"><div className="eyebrow">SETTINGS / PERSONALIZATION</div><h2>Make the machine yours.</h2><div className="settings-card"><div><strong>Appearance</strong><span>Choose how the portfolio workstation feels.</span></div><div className="toggle-line"><span>Light mode preview</span><button className={`toggle ${lightMode ? "toggle-on" : ""}`} onClick={() => setLightMode(!lightMode)}><i /></button></div></div><div className="settings-card wallpaper-setting"><div><strong>Wallpaper</strong><span>Fluent Signal · cyan systems field</span></div><div className="wallpaper-preview" style={{ backgroundImage: `url(${wallpaperUrl})` }}><span>Current</span></div></div><div className="settings-card"><div><strong>About this machine</strong><span>Bharani Systems · Portfolio OS · build 65.0.8</span></div><div className="settings-meta"><span>Signal Cyan</span><b>#00E0FF</b></div></div></div></div>;
}

export function CalculatorApp() {
  const [display, setDisplay] = useState("0");
  const press = (key: string) => { if (key === "C" || key === "CE") return setDisplay("0"); if (key === "=") { try { setDisplay(String(Function(`return ${display}`)())); } catch { setDisplay("Error"); } return; } setDisplay((value) => value === "0" || value === "Error" ? key : value + key); };
  return <div className="calculator-app"><div className="calculator-mode"><span>Standard</span><Menu size={16} /></div><div className="calc-display">{display}</div><div className="calc-grid">{["%", "CE", "C", "÷", "7", "8", "9", "×", "4", "5", "6", "-", "1", "2", "3", "+", "±", "0", ".", "="].map((key) => <button className={key === "=" ? "calc-equal" : ["÷", "×", "-", "+"].includes(key) ? "calc-op" : ""} onClick={() => press(key === "×" ? "*" : key === "÷" ? "/" : key)} key={key}>{key}</button>)}</div></div>;
}

export function WeatherApp() {
  return <div className="weather-app"><div className="weather-current"><div><div className="eyebrow">ATMOSPHERE / VELLORE</div><h2>29°</h2><p>Partly cloudy · feels like 32°</p><span>High 33° · Low 26°</span></div><CloudSun size={78} strokeWidth={1.1} /></div><div className="forecast-row">{[["NOW", "29°"], ["14:00", "31°"], ["17:00", "30°"], ["20:00", "28°"], ["23:00", "27°"]].map(([time, temp]) => <div key={time}><span>{time}</span><CloudSun size={20} /><strong>{temp}</strong></div>)}</div><div className="weather-note"><Radio size={16} /><span>Built as a calm visual weather dashboard. Open Atmosphere from the Live Demos browser to see the full experience.</span></div></div>;
}

export function NotificationPanel({ onClose }: { onClose: () => void }) {
  return <div className="notification-panel" onClick={(event) => event.stopPropagation()}><div className="notification-heading"><div><span className="eyebrow">SYSTEM CENTER</span><h3>Quick settings</h3></div><button onClick={onClose}><X size={15} /></button></div><div className="quick-grid"><button className="quick-active"><Wifi size={17} /><span>Wi-Fi</span><small>Connected</small></button><button className="quick-active"><Volume2 size={17} /><span>Sound</span><small>100%</small></button><button><SlidersHorizontal size={17} /><span>Focus</span><small>Off</small></button><button><ShieldCheck size={17} /><span>Privacy</span><small>Protected</small></button></div><div className="notification-card"><Zap size={16} /><div><strong>Portfolio index synced</strong><span>65 public repositories are ready to explore.</span></div></div><div className="notification-card"><Sparkles size={16} /><div><strong>Hidden signal detected</strong><span>There may be something interesting in the Secret folder.</span></div></div></div>;
}
